In [1]:
import numpy as np

In [8]:
# 1. داده‌های ورودی و خروجی
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # داده‌های ورودی (AND)
y = np.array([[0], [1], [1],
              [0]])             # خروجی (XOR)

In [3]:
# 2. مقداردهی اولیه وزن‌ها و بایاس‌ها
np.random.seed(42)
input_dim = 2
hidden_dim = 4
output_dim = 1

In [37]:
W1 = np.random.randn(input_dim, hidden_dim)  # وزن‌های لایه ورودی به پنهان
b1 = np.zeros((1, hidden_dim))               # بایاس لایه پنهان
W2 = np.random.randn(hidden_dim, output_dim) # وزن‌های لایه پنهان به خروجی
b2 = np.zeros((1, output_dim))               # بایاس لایه خروجی

In [16]:
# 3. توابع فعال‌سازی
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [97]:
# 4. آموزش مدل
learning_rate = 0.1
epochs = 10000

for epoch in range(epochs):
    # Forward Propagation
    Z1 = np.dot(X, W1) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(A1, W2) + b2
    A2 = sigmoid(Z2)

    # خطا
    loss = np.mean((y - A2)**2)

    # Backward Propagation
    dA2 = A2 - y
    dZ2 = dA2 * sigmoid_derivative(A2)
    dW2 = np.dot(A1.T, dZ2)
    db2 = np.sum(dZ2, axis=0, keepdims=True)

    dA1 = np.dot(dZ2, W2.T)
    dZ1 = dA1 * sigmoid_derivative(A1)
    dW1 = np.dot(X.T, dZ1)
    db1 = np.sum(dZ1, axis=0, keepdims=True)

    # به‌روزرسانی وزن‌ها و بایاس‌ها
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    
    # نمایش خطا در هر 1000 تکرار
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

Epoch 0, Loss: 0.0001
Epoch 1000, Loss: 0.0001
Epoch 2000, Loss: 0.0001
Epoch 3000, Loss: 0.0001
Epoch 4000, Loss: 0.0001
Epoch 5000, Loss: 0.0001
Epoch 6000, Loss: 0.0001
Epoch 7000, Loss: 0.0001
Epoch 8000, Loss: 0.0001
Epoch 9000, Loss: 0.0001


In [98]:
# 5. پیش‌بینی نهایی
def predict(X):
    Z1 = np.dot(X, W1) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(A1, W2) + b2
    A2 = sigmoid(Z2)
    return (A2 > 0.5).astype(int)

print("Predictions:")
print(predict(X))

Predictions:
[[0]
 [1]
 [1]
 [0]]


In [99]:
X_1 = np.array([[1, 1], [0, 0], [1, 1], [1, 1]])
predict(X_1)

array([[0],
       [0],
       [0],
       [0]])

In [100]:
X_2 = np.array([[0, 1], [1, 0], [1,0], [1, 0]])
predict(X_2)

array([[1],
       [1],
       [1],
       [1]])

In [ ]:
X_3 = np.array([[0, 1], [1, 0], [1,0], [1, 0]])
predict(X_3)